### ISSUE TITLE
Allow passing in request to "authenticated" function

### ISSUE THREAD

**Issue by johanhaleby** [remvee/ring-basic-authentication#20]
I have an app with two Jetty connectors, one for the management http interface and one for the external http interface (i.e. I have open two ports). I want different credentials for the management interface and external interface but this is not possible using this handler. I would like the `auth-fn` passed to `wrap-basic-authentication` to be able to accept the `request` parameter so that the `auth-fn` can make more advanced decisions. It would be good if the caller of `auth-fn` would support both options (both with- and without the `request` parameter)

**Comment by remvee** [comment]
You can easily make your own middleware and use `basic-authenication-request` function to do the authentication:

```
(ns my-auth
  (:require [ring.middleware.basic-authentication :as ba]))

(defn internal? [req] ...)
(defn internal-auth [user passwd] ...)
(defn external-auth [user passwd] ...)

(defn wrap [app & [realm denied-response]]
  (fn [req]
    (let [auth (if (internal? req) internal-auth external-auth)
          req (ba/basic-authentication-request req auth)]
      (if (:basic-authentication req)
        (app req)
        (ba/authentication-failure realm denied-response)))))
```

You can even vary the `realm` and `denied-response` that way.
