### ISSUE TITLE
Dependency on org.clojure/data.codec not required anymore

### ISSUE THREAD

**Issue by baldurmen** [remvee/ring-basic-authentication#21]
Hi!

It seem the dependency on [org.clojure/data.codec] is not required anymore.

Indeed, as mentioned in [this commit](https://github.com/clojure/data.codec/commit/8161193d3789e657ae0bed28c25d855ba1d1a407), the Base64 encoder has been provided by the JDK since Java 8.

**Comment by remvee** [comment]
Thank you for bringing this up; https://github.com/remvee/ring-basic-authentication/commit/951d74fdaf683b9fdaaa4de73ccb4235b2cfd28d
