### ISSUE TITLE
A body is incorrectly returned for an HEAD method on a 401 response.

### ISSUE THREAD

**Issue by brown131** [remvee/ring-basic-authentication#23]
According to RFC-2616: "The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. " (https://w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4). However, when a HEAD method returns an HTTP 401 Unauthorized response it returns a body "access denied". This breaks, in particular, the Cyberduck client app, which expects the server to be well-behaved.

**Comment by remvee** [comment]
Fix in 51362c5 and release with version 1.1.1.  Thanks for making this lib better.
